# Autogenerated wrapper script for libspecfemUtils_jll for x86_64-apple-darwin-libgfortran4
export libspecfemUtils

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libspecfemUtils")
JLLWrappers.@declare_library_product(libspecfemUtils, "@rpath/libspecfemUtils.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libspecfemUtils,
        "lib/libspecfemUtils.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
