# Autogenerated wrapper script for libspecfemUtils_jll for x86_64-linux-gnu-libgfortran5
export libspecfemUtils

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libspecfemUtils")
JLLWrappers.@declare_library_product(libspecfemUtils, "libspecfemUtils.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libspecfemUtils,
        "lib/libspecfemUtils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
